data:
    path:
        root: "data"
        raw: "data/Traffic_flow-HCM"
        preprocess: "data/preprocessed"

    files:
        nodes.csv:
        segment_status.csv:
        streets.csv:
            fillNaN: 
                fill_dict:
                    "max_velocity": -1
                    "name": "(không tên)"
            ordinalEncodingStreetLvl:
                column: "level"
                
        segments.csv:
            fillNaN:
                fill_dict:
                    "max_velocity": -1
                    "street_name": "(không tên)"
            rename:
                name_dict: 
                    _id: "segment_id"
            z_scoreStandardization:
                columns: ["length"] 
            oneHotEncoding:
                columns: ["street_type"]
            ordinalEncodingStreetLvl:
                column: "street_level"

        train.csv:
            weakFilter:
                threshold: 10
            periodExtraction: ~
            ordinalEncoding:
                map_dict:
                    A: 0
                    B: 1
                    C: 2
                    D: 3
                    E: 4
                    F: 5
            ordinalEncodingStreetLvl: 
                column: "street_level"
            oneHotEncoding: 
                columns: ["weekday", "street_type"]
    
    h5_path: "data/preprocessed/data.h5"
    graph_path: "data/preprocessed/dynamic.h5"
    dynamic_path: "data/preprocessed/dynamic.h5"
    static_path: "data/preprocessed/data.h5"

    gen_graph:
        T: 24 # Số bước quá khứ + tương lai
        P: 12 # Số bước quá khứ
        Q: 12 # Số bước tương lai

    split_ratio: [0.7, 0.2, 0.1] # train, val, test

train:
    STGNN:
        stgnn0: # Mặc định của tác giả
            d: 16 # Feature đầu ra của mỗi head attention
            F: 5 # Đặc trưng đầu vào
            V: 202 # Số nút
            L: 1 # Số block Statt
            overall:
                batch_size: 32
                epoch: 1
                dropout: 0.5
                learning_rate: 0.001
                optimizer: "SGD"
                regularization: "L2"
                init: "Xavier"
            